export const Subjects = [
    {
      name: "Construction Studies",
      group: "Practical",
      usage: "Secondary",
      Topics: [{ Topic: "Condensation & Air Tightness" },
  { Topic: "Conservation & Restoration" },
  { Topic: "Doors" },
  { Topic: "Drainage" },
  { Topic: "Fireplaces & Fire prevention" },
  { Topic: "Floors" },
  { Topic: "Foundations" },
  { Topic: "Heat & U value calculations" },
  { Topic: "Heat Loss & Insulation" },
  { Topic: "Hot Water & Space Heating" },
  { Topic: "Passive Design" },
  { Topic: "Planning, Sustainability & Environment" },
  { Topic: "Project & Practical" },
  { Topic: "Question One Drawing Questions" },
  { Topic: "Roofs" },
  { Topic: "Services: Water, Gas, Electricity.." },
  { Topic: "Site Safety" },
  { Topic: "Sound" },
  { Topic: "Stairs" },
  { Topic: "Sustainability & the Environment" },
  { Topic: "Walls" },
  { Topic: "Windows & Light" },
  { Topic: "Wood, rot & Ventilation" },],
    },{
      name: "Accounting",
      value: "accounting",
      group: "Practical",
      usage: "Primary",
      Topics: [{ Topic: "Budgeting-Cash"},  { Topic: "Budgeting-Production"},  { Topic: "Budgeting-Flexible"},  { Topic: "Cash Flow Statements"},  { Topic: "Club Accounts"},  { Topic: "Control Accounts"},  { Topic: "Correction of Errors/ Suspense"},  { Topic: "Costing-Job, Product, Stock Valuation & O/H Apportionment"},  { Topic: "Costing-Marginal"},  { Topic: "Depreciation of Fixed Assets"},  { Topic: "Farm Accounts"},  { Topic: "Final Accounts-Company"},  { Topic: "Final Accounts-Manufacturing"},  { Topic: "Final Accounts-Sole Trader"},  { Topic: "Fixed Assets Valuation"},  { Topic: "Incomplete Records A"},  { Topic: "Incomplete Records B"},  { Topic: "Interpretation of Accounts"},  { Topic: "Published Accounts"},  { Topic: "Revaluation of Fixed Assets"},  { Topic: "Service Firms"},  { Topic: "Tabular Statements"},],
    },
    { name: "Engineering", group: "Practical", usage: "Secondary", Topics: [] },
      { name: "Home Economics", group: "Practical", usage: "Secondary", Topics: [{ Topic: "Consumer Studies" },
  { Topic: "Diet & Health" },
  { Topic: "Elective1: Energy & Emissions" },
  { Topic: "Elective1: Heating, Water, Lighting.." },
  { Topic: "Elective1: Housing (Planning, building..)" },
  { Topic: "Elective1: Interior Design" },
  { Topic: "Elective2: Fabrics" },
  { Topic: "Elective2: Patterns & Fashion" },
  { Topic: "Elective3: (un)employment & Poverty" },
  { Topic: "Elective3: Education in Ireland" },
  { Topic: "Elective3: Family Life & Leisure" },
  { Topic: "Environment" },
  { Topic: "Food Assignments" },
  { Topic: "Food Industry & Packaging" },
  { Topic: "Food Spoilage & Food Safety" },
  { Topic: "Foods: Meat, Fish, Cereal, Fruit/Veg, Dairy, Eggs" },
  { Topic: "Household Appliances" },
  { Topic: "Household Finances" },
  { Topic: "Marriage & Family Law" },
  { Topic: "Meal Planning & Preparation" },
  { Topic: "Nutrition: Carbohydrates" },
  { Topic: "Nutrition: Lipids" },
  { Topic: "Nutrition: Protein" },
  { Topic: "Nutrition: Vitamins and Minerals" },
  { Topic: "Textiles" },
  { Topic: "The Family" },] },
  
    { name: "Technology", group: "Practical", usage: "Secondary", Topics: [] },
    { name: "Applied Maths", group: "Science", usage: "Secondary", Topics: [{ Topic: "Circular Motion and SHM" },{ Topic: "Collisions" },{ Topic: "Connected Particles " },{ Topic: "Differential Equations" },{ Topic: "Hydrostatics" },{ Topic: "Linear Motion " },{ Topic: "Moments of Inertia" },{ Topic: "Projectiles" },{ Topic: "Relative Velocity" },{ Topic: "Statics" },] },
    {
      name: "Agricultural Science",
      group: "Science",
      usage: "Primary",
      Topics: [
    { Topic: "Animal Diseases" },
    { Topic: "Animal Physiology" },
    { Topic: "Animal Production (All animals)" },
    { Topic: "Beef and Dairy Cattle" },
    { Topic: "Classification of Organisms" },
    { Topic: "Crop Production" },
    { Topic: "Describe an Experiment..." },
    { Topic: "Fertilisers, Pollution & the Environment" },
    { Topic: "Genetics" },
    { Topic: "Give a scientific explanation for..." },
    { Topic: "Grassland" },
    { Topic: "IDENTIFICATIONS - Animals" },
    { Topic: "IDENTIFICATIONS - Plants" },
    { Topic: "Pigs" },
    { Topic: "Sheep" },
    { Topic: "Soil Science" },
      ],
    },
    {
      name: "Biology",
      group: "Science",
      usage: "Primary",
      Topics: [
    { Topic: "Bacteria, Viruses, Fungi + Yeast" },
    { Topic: "Blood & Circulatory System" },
    { Topic: "Breathing System" },
    { Topic: "Cell Division" },
    { Topic: "Cell Metabolism & Enzymes" },
    { Topic: "Cell Structure" },
    { Topic: "Digestive System" },
    { Topic: "Ecology & Ecosystems" },
    { Topic: "Excretion" },
    { Topic: "Experiment Questions" },
    { Topic: "Eye/Ear & Nervous system" },
    { Topic: "Food & Food tests" },
    { Topic: "Genetics, DNA & Evolution" },
    { Topic: "Hormonal/Endrocrine System" },
    { Topic: "Human Reproduction" },
    { Topic: "Immune system" },
    { Topic: "Musculoskeletal System" },
    { Topic: "Photosynthesis" },
    { Topic: "Plant Reproduction" },
    { Topic: "Plant Responses & Seed growth" },
    { Topic: "Plant Structure" },
    { Topic: "Plant Transport and Osmosis" },
    { Topic: "Respiration" },
    { Topic: "The Scientific Method" },
      ],
    },
    {
      name: "Chemistry",
      group: "Science",
      usage: "Primary",
      Topics: [
    { Topic: "Acids, Bases & PH calculations" },
    { Topic: "Atomic Structure" },
    { Topic: "Chemical Equilibrium" },
    { Topic: "Electron Arrangement" },
    { Topic: "Experiment Q1 (Titration)" },
    { Topic: "Experiment Q2 (Organic)" },
    { Topic: "Experiment Q3 (Other)" },
    { Topic: "Fuels & Thermochemistry" },
    { Topic: "Gas Laws, moles & Gas Properties" },
    { Topic: "Instrumentation & Chromatography" },
    { Topic: "Ionic & Covalent Bonding" },
    { Topic: "Option: Atmospheric Chemistry" },
    { Topic: "Option: Industrial Chemistry" },
    { Topic: "Option: Materials & Polymers" },
    { Topic: "Option: Metals" },
    { Topic: "Organic Chemistry" },
    { Topic: "Oxidation & Reduction" },
    { Topic: "Periodic Table" },
    { Topic: "Radioactivity" },
    { Topic: "Rates of Reaction" },
    { Topic: "Stoichiometry, Formulae & Equations" },
    { Topic: "Water & Water Analysis" },
      ],
    },
    {
      name: "Mathematics",
      group: "Science",
      usage: "Primary",
      Topics: [
    { Topic: "Algebra" },
    { Topic: "Area & Volume" },
    { Topic: "Complex Numbers" },
    { Topic: "Co-Ordinate Geometry, The Line" },
    { Topic: "Differentiation" },
    { Topic: "Financial Maths/Arithmetic" },
    { Topic: "Functions" },
    { Topic: "Geometry" },
    { Topic: "Geometry (Proofs and Constructions)" },
    { Topic: "Graphs of Functions" },
    { Topic: "Induction" },
    { Topic: "Integration" },
    { Topic: "Logs" },
    { Topic: "Probability" },
    { Topic: "Roots of a Function/ Equation" },
    { Topic: "Sequences & Series" },
    { Topic: "Sets" },
    { Topic: "Statistics & Data" },
    { Topic: "The Circle" },
    { Topic: "Trigonometry" },
      ],
    },
    {
      name: "Geography",
      group: "Science",
      usage: "Secondary",
      Topics: [
    { Topic: "Aerial photos" },{ Topic: "Earthquakes & Volcanoes" },{ Topic: "Economic - Developing Economies" },{ Topic: "Economic - Energy" },{ Topic: "Economic - Enviromental impact" },{ Topic: "Economic - European Union" },{ Topic: "Economic - Multinationals & Globalisation" },{ Topic: "Elective - Economic" },{ Topic: "Elective - Human" },{ Topic: "Glaciation" },{ Topic: "Human - Population" },{ Topic: "Human - Urban Geography" },{ Topic: "Karst Regions" },{ Topic: "Mapwork" },{ Topic: "Option - Atmosphere & Ocean" },{ Topic: "Option - Culture & Identity" },{ Topic: "Option - Geoecology" },{ Topic: "Option - Global Interdependence" },{ Topic: "Plate Tectonics" },{ Topic: "PROJECT - Investigation" },{ Topic: "Regions - Continental" },{ Topic: "Regions - European" },{ Topic: "Regions - Ireland" },{ Topic: "Rivers" },{ Topic: "Rocks, Weathering & Mass Movement" },{ Topic: "Tables/Graphs Questions" },{ Topic: "The Sea" },{ Topic: "Urban Land uses" },{ Topic: "Weather & Climate" },
      ],
    },
     {
      name: "Economics",
      group: "Science",
      usage: "Secondary",
      Topics: [{ Topic: "(Old Course) Consumer and Utility" },
  { Topic: "(Old Course) Costs of Production, Revenue & Profit" },
  { Topic: "(Old Course) Economic Growth & Development" },
  { Topic: "(Old Course) Economic Policies: Problems & Conflict" },
  { Topic: "(Old Course) Economists (Keynes, Smith, Marx...)" },
  { Topic: "(Old Course) Factors of Production - Capital" },
  { Topic: "(Old Course) Factors of Production - Enterprise" },
  { Topic: "(Old Course) Factors of Production - Land" },
  { Topic: "(Old Course) Money & Banking" },
  { Topic: "(Old Course) The Government and the Economy" },
  { Topic: "1.1 Economic Concepts" },
  { Topic: "1.2 Sustainability" },
  { Topic: "2.1 The Market Economy" },
  { Topic: "2.2 Elasticity" },
  { Topic: "2.3 Costs of Production, Revenue + Profit" },
  { Topic: "2.4 Government Intervention" },
  { Topic: "3.1 Market Structures" },
  { Topic: "3.2 The Labour Market " },
  { Topic: "3.3 Market Failure" },
  { Topic: "4.1 National income" },
  { Topic: "4.2 Fiscal Policy and the Budget Framework" },
  { Topic: "4.3 Employment" },
  { Topic: "4.4 Monetary Policy and Price Level" },
  { Topic: "4.5 The Financial Sector" },
  { Topic: "5.1 Economic Growth and Development" },
  { Topic: "5.2 Globalisation" },
  { Topic: "5.3 International Trade and Competitiveness" },
  { Topic: "6.1 Topical Questions and Statistics" },
  { Topic: "Research Project" },],
    },
    {
      name: "Physics",
      group: "Science",
      usage: "Secondary",
      Topics: [
    { Topic: "Acceleration" },
    { Topic: "Applied Electricity" },
    { Topic: "Circular Motion" },
    { Topic: "Current & Charge" },
    { Topic: "Electric Circuits" },
    { Topic: "Electromagnetic Induction" },
    { Topic: "Exp. Qs (all)" },
    { Topic: "Exp. Qs. -  Electricity" },
    { Topic: "Exp. Qs. -  Heat" },
    { Topic: "Exp. Qs. -  Light" },
    { Topic: "Exp. Qs. -  Mechanics" },
    { Topic: "Exp. Qs. -  Sound" },
    { Topic: "Force,Mass & Momentum" },
    { Topic: "Heat & Heat Transfer" },
    { Topic: "Light" },
    { Topic: "Magnets and Magnetic Fields" },
    { Topic: "Nuclear Energy" },
    { Topic: "Particle Physics" },
    { Topic: "Potential Difference & Capacitance" },
    { Topic: "Pressure, Gravity & Moments" },
    { Topic: "Reflection & Mirrors" },
    { Topic: "Refraction & Lenses" },
    { Topic: "Resistance" },
    { Topic: "Semiconductors" },
    { Topic: "Simple Harmonic Motion" },
    { Topic: "Speed, Displacement, Velocity" },
    { Topic: "Static Electricity" },
    { Topic: "Temperature & Thermometers" },
    { Topic: "The Atom, Nucleus & Radioactivity" },
    { Topic: "The Electron" },
    { Topic: "Vectors & Scalars" },
    { Topic: "Vibration & Sound" },
    { Topic: "Waves & Wave Motion" },
    { Topic: "Work, Energy & Power" },
      ],
    },
    {
      name: "Physics and Chemistry",
      group: "Science",
      usage: "Secondary",
      Topics: [],
    },
    {
      name: "Computer Science",
      group: "Science",
      usage: "Secondary",
      Topics: [],
    },
    { name: "Art", group: "Artistic", usage: "Secondary", Topics: [
      { Topic: "Appreciation - Architecture and Renovation" },
  { Topic: "Appreciation - Fashion/Clothing & Jewelry Design" },
  { Topic: "Appreciation - Film Studies" },
  { Topic: "Appreciation - Gallery Visit" },
  { Topic: "Appreciation - Graphic Design" },
  { Topic: "Appreciation - Product Design" },
  { Topic: "Appreciation - Public/Street Art" },
  { Topic: "Early Christian Ireland - Manuscripts" },
  { Topic: "Early Christian Ireland - Metalwork" },
  { Topic: "Early Christian Ireland - Stonework" },
  { Topic: "Europe - Gothic & Romanesque Architecture" },
  { Topic: "Europe - Impressionist" },
  { Topic: "Europe - Medieval" },
  { Topic: "Europe - Post Impressionism" },
  { Topic: "Europe - Renaissance" },
  { Topic: "Europe - Romantic Period" },
  { Topic: "Europe - Surrealism/Cubism" },
  { Topic: "Generic Qs - Categories" },
  { Topic: "Generic Qs - Movements" },
  { Topic: "Ireland - Georgian Architecture and Arts" },
  { Topic: "Ireland - Modern Artists and Designers" },
  { Topic: "Ireland - Romantic Period" },
  { Topic: "Pre Christian - Bronze Age" },
  { Topic: "Pre Christian - Iron Age" },
  { Topic: "Pre-Christian - Burial and monastic sites" },
    ] },
    { name: "Music", group: "Artistic", usage: "Secondary", Topics: [] },
    {
      name: "Design & Comm Graphics",
      group: "Artistic",
      usage: "Secondary",
      Topics: [],
    },
    { name: "Arabic", group: "Humanities", usage: "Secondary", Topics: [] },
    {
      name: "Classical Studies",
      group: "Humanities",
      usage: "Secondary",
      Topics: [],
    },
    {
      name: "English",
      group: "Humanities",
      usage: "Primary",
      Topics: [
    { Topic: "Composition (Personal Writing)" },
    { Topic: "Reading Comprehension" },
    { Topic: "Comparative - Cultural Context " },
    { Topic: "Comparative - Literary genre (2020)" },
    { Topic: "Comparative - Theme or Issue" },
    { Topic: "Comparative - Vision & Viewpoint (2021)" },
    { Topic: "Hamlet (2020)" },
    { Topic: "King Lear" },
        { Topic: "Macbeth" },
  
    { Topic: "Othello" },
    { Topic: "Poetry - Bishop (2021)" },
    { Topic: "Poetry - Boland (2020/21)" },
    { Topic: "Poetry - Dickinson (2020)" },
    { Topic: "Poetry - Durcan (2020/21)" },
    { Topic: "Poetry - Frost (2020/21)" },
    { Topic: "Poetry - Heaney (2021)" },
    { Topic: "Poetry - Hopkins (2021)" },
    { Topic: "Poetry - Yeats (2021)" },
    { Topic: "Poetry - Keats (2021)" },
  
    { Topic: "Poetry - Lawrence (2020)" },
    { Topic: "Poetry - Ni Chuilleanain (2020)" },
    { Topic: "Poetry - Plath (2021)" },
    { Topic: "Poetry - Rich (2020)" },
    { Topic: "Poetry - Wordsworth (2020)" },
        {
          Topic: "Text - (2021) Persepolis: The Story of a Childhood and the Story of a Return",
        },
    { Topic: "Text - All My Sons" },
    { Topic: "Text - Americanah" },
    { Topic: "Text - Never Let me Go (2021)" },
    { Topic: "Text - Persuasion " },
    { Topic: "Text - The Great Gatsby " },
    { Topic: "Text - The Handmaid's Tale" },
    { Topic: "Text - Wuthering Heights " },
    { Topic: "The Tempest" },
    { Topic: "Unseen Poetry" },
      ],
    },
    {
      name: "French",
      group: "Humanities",
      usage: "Primary",
      Topics: [
    { Topic: "AURAL - Conversation" },
    { Topic: "AURAL - Interview " },
    { Topic: "AURAL - News Pieces" },
    { Topic: "Literary/Novel Comprehension" },
    { Topic: "Newspaper/Magazine Comprehension" },
    { Topic: "Opinion - Animals, nature and the environment" },
    { Topic: "Opinion - Education" },
    { Topic: "Opinion - Health" },
    { Topic: "Opinion - Ireland, travel, tourism and culture" },
    { Topic: "Opinion - Politics, social issues and equality" },
    { Topic: "Opinion - Sport" },
    { Topic: "Opinion - Technology and media" },
    { Topic: "Opinion - Youth, teenagers and families" },
    { Topic: "ORAL exam" },
    { Topic: "Write a Diary..." },
    { Topic: "Write a letter..." },
    { Topic: "Write a Note..." },
    { Topic: "Write an eMail..." },
    { Topic: "Written Production (recit)" },
      ],
    },
    {
      name: "Irish",
      group: "Humanities",
      usage: "Secondary",
      Topics: [
    { Topic: "AURAL - ComhrÃ¡ (Conversation)" },
    { Topic: "AURAL - PhÃ­osa Nuachta (News Pieces)" },
    { Topic: "AURALS - FÃ³gra (Announcement)" },
    { Topic: "ORAL exam" },
    { Topic: "Poetry - An SpailpÃ­n FÃ¡nach" },
    { Topic: "Poetry - An tEarrach Thiar" },
    { Topic: "Poetry - Colscaradh" },
    { Topic: "Poetry - GÃ©ibheann" },
    { Topic: "Poetry - Mo GhrÃ¡-sa" },
    { Topic: "Poetry, extra - A Chlann" },
    { Topic: "Poetry, extra - Caoineadh AUL" },
    { Topic: "Poetry, extra - ColmÃ¡in " },
    { Topic: "Poetry, extra - Eiceolai" },
    { Topic: "Poetry, extra - Fill Aris" },
    { Topic: "Prose - A thig NÃ¡ Tit Orm" },
    { Topic: "Prose - An GnÃ¡thrud" },
    { Topic: "Prose - An Lasair Choille" },
    { Topic: "Prose - An Triail" },
    { Topic: "Prose - CÃ¡ca Milis" },
    { Topic: "Prose - Canary Wharf" },
    { Topic: "Prose - DÃ­s" },
    { Topic: "Prose - Gafa" },
    { Topic: "Prose - Hurlamaboc" },
    { Topic: "Prose - OisÃ­n I dtÃ­r na nÃ“g" },
    { Topic: "Prose - TÃ³raÃ­ocht Dhiarmada agus GhrÃ¡inne" },
    { Topic: "Reading Comprehension" },
    { Topic: "Studied Poetry (Filiocht Roghnach)" },
    { Topic: "Studied Prose (Pros Roghnach)" },
    { Topic: "Write a Debate.." },
    { Topic: "Write a News/Magazine Article.." },
    { Topic: "Write a Story.." },
    { Topic: "Write an Essay.." },
      ],
    },
    {
      name: "Hebrew Studies",
      group: "Humanities",
      usage: "Secondary",
      Topics: [],
    },
    {
      name: "German",
      group: "Humanities",
      usage: "Secondary",
      Topics: [
    { Topic: "AURAL - 1) Interview " },
    { Topic: "AURAL - 2) Phone Call" },
    { Topic: "AURAL - 3) Dialogue" },
    { Topic: "AURAL - 4) News Pieces" },
    { Topic: "Ã„uÃŸerung zum Thema (Write on a theme)" },
    { Topic: "Comprehension: Magazine or Newspaper" },
    { Topic: "Comprehension: Novel or Short story" },
    { Topic: "Grammatik (Grammar)" },
    { Topic: "ORAL exam" },
    { Topic: "Schriftliche Produktion (Picture)" },
    { Topic: "Schriftliche Produktion (Write a Letter)" },
      ],
    },
    {
      name: "History",
      group: "Humanities",
      usage: "Secondary",
      Topics: [
    { Topic: "1.IRL Ireland & the Union" },
    { Topic: "2.IRL Movements for political/social reform" },
    { Topic: "3.IRL Sovereignty & the impact of partition" },
    { Topic: "4.IRL The Irish diaspora" },
    { Topic: "5.IRL Politics & Society in Northern Ireland" },
    { Topic: "6.IRL Republic - government, society, economy" },
    { Topic: "EUR1. Nationalism & state formation" },
    { Topic: "EUR2. Nation states & international tensions" },
    { Topic: "EUR3. Dictatorship & Democracy" },
    { Topic: "EUR4. Division & Realignment" },
    { Topic: "EUR5. Retreat from Empire & aftermath" },
    { Topic: "EUR6. The United States & the World" },
    { Topic: "Leaving Cert History Later Modern " },
      ],
    },
    {
      name: "Italian",
      group: "Humanities",
      usage: "Secondary",
      Topics: [
    { Topic: "AURAL - Conversations" },
    { Topic: "Aural - News items/statements" },
    { Topic: "Essay Writing (A ciascuno)" },
    { Topic: "Essay Writing (Bianca)" },
    { Topic: "Oral" },
    { Topic: "Reading Comprehension (A ciascuno...)" },
    { Topic: "Reading Comprehension (Bianca...) " },
    { Topic: "Reading Comprehension (Journalistic)" },
    { Topic: "Reading Comprehension (Literary - Unseen)" },
    { Topic: "Written Composition - Formal" },
    { Topic: "Written Composition - Guided" },
    { Topic: "Written Composition - Opinion Piece" },
      ],
    },
    { name: "Japanese", group: "Humanities", usage: "Secondary", Topics: [] },
    { name: "Latin", group: "Humanities", usage: "Secondary", Topics: [] },
    { name: "Russian", group: "Humanities", usage: "Secondary", Topics: [] },
    {
      name: "Spanish",
      group: "Humanities",
      usage: "Primary",
      Topics: [
    { Topic: "Aural - Anuncio/ Announcement" },
    { Topic: "Aural - Descriptivo/ Description" },
    { Topic: "Aural - Dialogo/ Dialogue" },
    { Topic: "Aural - El Tiempo/ Weather" },
    { Topic: "Aural - Una Noticia/News" },
    { Topic: "Journalistic Text" },
    { Topic: "Opinion Text" },
    { Topic: "ORAL exam" },
    { Topic: "Prescribed Literature (Sin Noticias de Gurb)" },
    { Topic: "Short Comprehensions" },
    { Topic: "Write a Dialogue..." },
    { Topic: "Write a Letter/email..." },
    { Topic: "Writer a Diary entry/note..." },
    { Topic: "Leaving Cert Spanish Discussions" },
      ],
    },
    
    {
      name: "Ancient Greek",
      group: "Humanities",
      usage: "Secondary",
      Topics: [],
    },
  ];
  export default Subjects